language: node_js
node_js:
  - "node"
  - "7"

before_install:
  - npm install -g yarn
  - yarn install

cache:
  yarn: true

script: 
  - echo "Testing...!"
  - yarn codecov

install:
  - echo "Installing firebase-tools..."
  - yarn add global firebase-tools gh-pages
  - echo "Installing success!"

after_success:
  - echo "Deploying..."
  - npm run build
  - gh-pages -d build
  - echo "github-pages building...success!!"
  - firebase deploy --token $FIREBASE_TOKEN
  - echo "firebase Success!"