language: node_js
node_js:
  - "node"
  - "7"
cache:
  yarn: true

before_script:
  - echo "Initializing prevent installing"
  - npm install -g yarn
  - yarn install

script: 
  - echo "Testing...!"
  - yarn codecov

install:
  - echo "Installing firebase-tools..."
  - yarn add global firebase-tools
  - echo "Installing success!"
after_success:
  - echo "Deploying..."
  - firebase deploy --token $FIREBASE_TOKKEN
  - echo "CI Success!"